# Site settings
title:         虤
description:    "虤，二虎博客，二只老虎，熊的猫，标准城市空巢青年。本博客基于Jekyll进行书写。源自生活的点点滴滴和碎碎念。"
baseurl:        ""
url:            "https://2hu.net"

# Author
author:
  name:         熊的猫
  url:          https://2hu.net/about/
  email:        8200@88.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:      /post/:year:month:day.html
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, muji.gemspec ]
